from .BookingView import BookingRetrieveUpdateDestroyView
from .BookingView import BookingListCreateView
from .ImageView import ImageRetrieveUpdateDestroyView
from .ImageView import ImageView
from .SponsorView import SponsorView
from .PricingView import PricingView
from .CategoryView import CategoryListCreateView
from .CategoryView import CategoryRetrieveUpdateDestroyView
from .EventView import EventListCreateView
from .EventView import EventRetrieveUpdateDestroyView
from .NewsView import NewsView
from .TagView import TagView
