from .BookingView import BookingListCreateView
from .BookingView import BookingRetrieveUpdateDestroyView
from .CategoryView import CategoryListCreateView
from .CategoryView import CategoryRetrieveUpdateDestroyView
from .EventView import EventListCreateView
from .EventView import EventRetrieveUpdateDestroyView
from .ImageView import ImageListCreateView
from .ImageView import ImageRetrieveUpdateDestroyView
from .NewsView import NewsListCreateView
from .NewsView import NewsRetrieveUpdateDestroyView
from .PricingView import PricingListCreateView
from .PricingView import PricingRetrieveUpdateDestroyView
from .SponsorView import SponsorListCreateView
from .SponsorView import SponsorRetrieveUpdateDestroyView
from .TagView import TagRetrieveUpdateDestroyView
from .TagView import TagView
from .TeamMemberView import TeamMemberListCreateView, TeamMemberRetrieveUpdateDestroyView
from .TournamentView import TournamentListCreateView, TournamentRetrieveUpdateDestroyView
from .TrainingView import TrainingListCreateView, TrainingRetrieveUpdateDestroyView
from .UserAdminView import UserAdminView
from .UserRegisterView import UserRegisterView
