# TODO : fix circular import when SHIFT + O
from .BookingSerializer import BookingSerializer
from .CategorySerializer import CategorySerializer
from .TagSerializer import TagSerializer
from .ImageSerializer import ImageSerializer, ImageDetailSerializer
from .SponsorSerializer import SponsorSerializer, SponsorDetailSerializer
from .PricingSerializer import PricingSerializer
from .EventSerializer import EventSerializer, EventDetailSerializer
from .NewsSerializer import NewsSerializer, NewsDetailSerializer
from .ProfessorSerializer import ProfessorSerializer, ProfessorDetailSerializer
from .TeamMemberSerializer import TeamMemberSerializer, TeamMemberDetailSerializer
from BackendTennis.serializers.page_serializer.TeamPageSerializer import TeamPageSerializer, TeamPageDetailSerializer
from .TournamentSerializer import TournamentSerializer, TournamentDetailSerializer
from .TrainingSerializer import TrainingSerializer, TrainingDetailSerializer
from .ClubValueSerializer import ClubValueSerializer
from BackendTennis.serializers.page_serializer.AboutPageSerializer import AboutPageSerializer, AboutPageDetailSerializer
from .RouteSerializer import RouteSerializer
from .MenuItemSerializer import MenuItemSerializer, MenuItemDetailSerializer
from BackendTennis.serializers.page_serializer.HomePageSerializer import HomePageSerializer, HomePageDetailSerializer
from .RenderSerializer import RenderSerializer
from .PageRenderSerializer import PageRenderSerializer, PageRenderDetailSerializer
