# Generated by Django 4.1.7 on 2023-04-05 16:08

import BackendTennis.utils
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=BackendTennis.utils.create_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('clientFirstName', models.CharField(max_length=50)),
                ('clientLastName', models.CharField(max_length=50)),
                ('clientEmail', models.EmailField(max_length=100)),
                ('clientPhoneNumber', models.CharField(max_length=30)),
                ('payed', models.BooleanField(default=False)),
                ('insurance', models.BooleanField(default=False)),
                ('color', models.CharField(default='red', max_length=50)),
                ('label', models.CharField(default='Réservé', max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=BackendTennis.utils.create_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to=BackendTennis.utils.compute_image_url)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.CharField(default=BackendTennis.utils.create_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=100, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sponsor', to='BackendTennis.image')),
            ],
        ),
    ]
