# Generated by Django 4.1.7 on 2024-07-31 10:04

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_super_user(apps, schema_editor):
    User = apps.get_model('BackendTennis', 'User')  # Remplacez 'your_app_name' par le nom de votre application
    # Créez l'utilisateur si nécessaire
    if not User.objects.filter(email='test@test.com').exists():
        super_user = User(
            first_name="Super",
            last_name="User",
            birthdate="1900-01-01",
            email="test@test.com",
            phone_number="+12025550123",
            postal_code="12345",
            address="1234 Admin Rd",
            street="Admin Rd",
            city="Admin City",
            country="Admin Country",
            password=make_password("test")
        )
        super_user.is_superuser = True
        super_user.is_staff = True
        super_user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0002_alter_event_end_alter_event_start_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RunPython(create_super_user),
    ]
