# Generated by Django 4.1.7 on 2024-08-01 15:25

import BackendTennis.models.UserManager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendTennis', '0003_auto_20240731_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['createAt']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        )
    ]
