# Generated by Django 4.1.7 on 2024-10-23 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0007_remove_pricing_description_adding_pricing_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='extra_data',
            new_name='extraData',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='site_access',
            new_name='siteAccess',
        ),
    ]
