# Generated by Django 4.1.7 on 2024-10-24 14:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0010_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('image',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members',
                                   to='BackendTennis.image')),
            ],
        ),
    ]
