# Generated by Django 4.1.7 on 2024-10-24 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0011_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order']},
        ),
    ]
