# Generated by Django 4.1.7 on 2024-10-25 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BackendTennis', '0013_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('professorsTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('professorsDescription', models.TextField(blank=True, null=True)),
                ('teamMembersTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('dataCounter', models.JSONField(blank=True, default=list, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('professors', models.ManyToManyField(related_name='team_pages', to='BackendTennis.professor')),
                ('teamMembers', models.ManyToManyField(related_name='team_pages', to='BackendTennis.teammember')),
            ],
        ),
    ]
