# Generated by Django 4.1.7 on 2024-10-28 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BackendTennis', '0015_clubvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clubTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('clubDescription', models.TextField(blank=True, null=True)),
                ('dataCounter', models.JSONField(blank=True, default=list, null=True)),
                ('clubValueTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsorTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('clubImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_pages', to='BackendTennis.image')),
                ('clubValues', models.ManyToManyField(blank=True, null=True, related_name='about_pages', to='BackendTennis.clubvalue')),
                ('sponsors', models.ManyToManyField(blank=True, null=True, related_name='about_pages', to='BackendTennis.sponsor')),
            ],
        ),
    ]
