# Generated by Django 4.1.7 on 2024-10-28 14:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0017_alter_aboutpage_clubvalues_alter_aboutpage_sponsors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], max_length=100)),
                ('domainUrl', models.CharField(max_length=255)),
                ('pathUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('componentPath', models.CharField(blank=True, max_length=255, null=True)),
                ('metaTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('metaTags', models.JSONField(default=list)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
