# Generated by Django 4.1.7 on 2024-10-28 15:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0018_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='menu_item_rows', to='BackendTennis.route')),
            ],
        ),
    ]
