# Generated by Django 4.1.7 on 2024-10-29 08:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0019_menuitemrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('image',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items',
                                   to='BackendTennis.image')),
                ('route',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items',
                                   to='BackendTennis.route')),
                ('rows', models.ManyToManyField(related_name='menu_items', to='BackendTennis.menuitemrow')),
            ],
        ),
    ]
