# Generated by Django 4.1.7 on 2024-10-29 09:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0020_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('menuItems', models.ManyToManyField(related_name='home_pages', to='BackendTennis.menuitem')),
            ],
        ),
    ]
