# Generated by Django 4.1.7 on 2024-10-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendTennis', '0021_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='rows',
        ),
        migrations.DeleteModel(
            name='MenuItemRow',
        ),
    ]
