# Generated by Django 4.1.7 on 2024-10-29 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BackendTennis', '0022_remove_menuitem_rows_delete_menuitemrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('navBarPosition', models.CharField(choices=[('left', 'LEFT'), ('center', 'CENTER'), ('right', 'RIGHT')], max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('nav_bar', 'NAV_BAR'), ('home_page', 'HOME_PAGE')], max_length=100)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('isButton', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
