# Generated by Django 4.1.7 on 2024-10-29 15:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0023_render'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_renders',
                                             to='BackendTennis.render')),
                ('route',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_renders',
                                   to='BackendTennis.route')),
            ],
        ),
    ]
