# Generated by Django 4.1.7 on 2024-10-29 16:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0024_pagerender'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('childrenNavigationItems',
                 models.ManyToManyField(related_name='parent_navigation_items', to='BackendTennis.navigationitem')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='navigation_items', to='BackendTennis.image')),
                ('navBarRender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='navigation_items', to='BackendTennis.render')),
                ('pageRenders', models.ManyToManyField(related_name='navigation_items', to='BackendTennis.pagerender')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='navigation_items', to='BackendTennis.route')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='menuItems',
            field=models.ManyToManyField(related_name='home_pages', to='BackendTennis.navigationitem'),
        ),
    ]
