# Generated by Django 4.1.7 on 2024-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0025_navigationitem_delete_menuitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationitem',
            name='order',
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
