# Generated by Django 4.1.7 on 2024-10-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendTennis', '0028_remove_navigationbar_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='menuItems',
            new_name='navigationsItems',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
