# Generated by Django 4.1.7 on 2024-10-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendTennis', '0029_rename_menuitems_homepage_navigationsitems_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='navigationsItems',
            new_name='navigationItems',
        ),
    ]
