# Generated by Django 4.1.7 on 2024-10-30 15:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0030_rename_navigationsitems_homepage_navigationitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('pricing', models.ManyToManyField(blank=True, null=True, related_name='pricing_pages',
                                                   to='BackendTennis.pricing')),
            ],
        ),
    ]
