# Generated by Django 4.1.7 on 2024-11-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0032_alter_pricingpage_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='navigation_items', to='BackendTennis.image'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='navBarRender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='navigation_items', to='BackendTennis.render'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='navigation_items', to='BackendTennis.route'),
        ),
    ]
