# Generated by Django 4.1.7 on 2024-11-13 10:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BackendTennis', '0035_remove_teammember_fullname_remove_teammember_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='fullNames',
        ),
        migrations.AddField(
            model_name='teammember',
            name='fullNames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True,
                                                            default=list, size=None),
        ),
    ]
